# ##                          ##
# ##         EasyAuth         ##
# ##  Storage Configuration   ##
# ##                          ##
# 
# Note: If your string contains special characters, you should enclose it in double quotes.

# Database type. Can be sqlite, mysql, mongodb or postgresql. SQLite is set by default.
database-type=sqlite
# 
# SQLite configuration.
sqlite {
    # 
    # SQLite database path.
    sqlite-path="EasyAuth/easyauth.db"
    # 
    # SQLite table name.
    sqlite-table=easyauth
}
# 
# MySQL configuration.
mysql {
    # 
    # MySQL host.
    mysql-host=localhost
    # 
    # MySQL user.
    mysql-user=root
    # 
    # MySQL password.
    mysql-password=password
    # 
    # MySQL database.
    mysql-database=easyauth
    # 
    # MySQL table name.
    mysql-table=easyauth
}
# 
# MongoDB configuration.
mongodb {
    # 
    # MongoDB connection string.
    mongodb-connection-string="mongodb://username:password@host:port/?options"
    # 
    # MongoDB database name.
    mongodb-database=easyauth
}
# 
# PostgreSQL configuration.
postgresql {
    # 
    # PostgreSQL host and port (e.g. localhost:5432).
    pg-host="localhost:5432"
    # 
    # PostgreSQL user.
    pg-user=postgres
    # 
    # PostgreSQL password.
    pg-password=password
    # 
    # PostgreSQL database name.
    pg-database=easyauth
    # 
    # PostgreSQL table name.
    pg-table=easyauth
}
