##                          ##
##         BlueMap          ##
##       Core-Config        ##
##                          ##

# Accept Mojang EULA for resource download
accept-download: true

# Data folder
data: "bluemap"

# Render threads (2 is good for Ryzen 5 2600)
render-thread-count: 2

# Scan for mod resources (important for custom structures!)
scan-for-mod-resources: true

# Disable metrics
metrics: false

# Debug logging
log: {
  file: "bluemap/logs/debug.log"
  append: false
}
